# Generated by Django 3.0.7 on 2020-06-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Climb')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Session')),
            ],
        ),
    ]
