# Generated by Django 3.0.7 on 2020-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_climbingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
