# Generated by Django 3.1.2 on 2020-11-22 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0004_auto_20200622_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auth.user'),
            preserve_default=False,
        ),
    ]
