# Generated by Django 3.1.2 on 2020-11-22 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0005_session_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climb_owner', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='journal.session'),
        ),
    ]
