# Generated by Django 3.1.2 on 2021-05-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0006_auto_20201122_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='climb_type',
            field=models.CharField(default='Flash', max_length=20),
        ),
        migrations.AddField(
            model_name='climb',
            name='takes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='climb',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_climbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
