# Generated by Django 3.1.2 on 2021-09-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20210513_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='journal.session')),
            ],
        ),
    ]
