# Generated by Django 3.1.2 on 2021-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20210921_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='comments',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
